CREATE TABLE AIRCRAFTDIM
(
AC_ID INT IDENTITY(1,1) NOT NULL,
MOD_CODE VARCHAR(25),
MOD_NAME VARCHAR(25)
);

CREATE TABLE PILOTDIM
(
PILOT_ID INT IDENTITY(1,1) NOT NULL,
EMP_NUM INT NOT NULL,
EMP_LNAME VARCHAR (15),
EMP_FNAME VARCHAR (15)	
);

CREATE TABLE TIMEDIM
(
TIME_ID INT IDENTITY(1,1) NOT NULL,
CHAR_DATE DATETIME NOT NULL,
CHAR_YEAR INT NOT NULL,
CHAR_MONTH INT NOT NULL,
CHAR_DAY INT NOT NULL
);

CREATE TABLE FACT
(
AC_ID INT NOT NULL,
PILOT_ID INT NOT NULL,
TIME_ID INT NOT NULL,
FUELUSED FLOAT,
DISTANCE FLOAT,
REVENUE FLOAT
);

ALTER TABLE AIRCRAFTDIM
ADD CONSTRAINT ACDIM_PK PRIMARY KEY (AC_ID)

ALTER TABLE PILOTDIM
ADD CONSTRAINT PILOTDIM_PK PRIMARY KEY (PILOT_ID)

ALTER TABLE TIMEDIM
ADD CONSTRAINT TIMEDIM_PK PRIMARY KEY (TIME_ID)

ALTER TABLE FACT
ADD CONSTRAINT FACT_PK PRIMARY KEY (AC_ID, PILOT_ID, TIME_ID)

ALTER TABLE FACT
ADD CONSTRAINT FACT_FK FOREIGN KEY (AC_ID) REFERENCES AIRCRAFTDIM (AC_ID),
			   FOREIGN KEY (PILOT_ID) REFERENCES PILOTDIM (PILOT_ID),
			   FOREIGN KEY (TIME_ID) REFERENCES TIMEDIM (TIME_ID)

CREATE TABLE STAGING
(
AC_ID INT,
PILOT_ID INT,
TIME_ID INT,
FUELUSED FLOAT,
DISTANCE FLOAT,
REVENUE FLOAT,
MOD_CODE VARCHAR(20) NOT NULL,
MOD_NAME VARCHAR(20),
EMP_NUM INT NOT NULL,
EMP_LNAME VARCHAR (25),
EMP_FNAME VARCHAR (25),
CHAR_DATE DATETIME NOT NULL, 
CHAR_YEAR INT NOT NULL,
CHAR_MONTH INT NOT NULL,
CHAR_DAY INT NOT NULL
);

--ALTER TABLE FACT DROP CONSTRAINT FACT_PK
--ALTER TABLE FACT DROP CONSTRAINT FACT_FK
--ALTER TABLE AIRCRAFTDIM DROP CONSTRAINT ACDIM_PK
--ALTER TABLE PILOTDIM DROP CONSTRAINT PILOTDIM_PK
--ALTER TABLE TIMEDIM DROP CONSTRAINT TIMEDIM_PK
--DROP TABLE TIMEDIM, FACT, PILOTDIM, AIRCRAFTDIM, STAGING

