CREATE PROCEDURE A10SP
AS
BEGIN
	--DROP FOREIGN KEY CONSTRAINT
	ALTER TABLE FACT DROP CONSTRAINT FACT_FK

	--TRUNCATE ALL TABLES TO REMOVE THE DATA
	TRUNCATE TABLE AIRCRAFTDIM
	TRUNCATE TABLE PILOTDIM
	TRUNCATE TABLE TIMEDIM
	TRUNCATE TABLE STAGING
	TRUNCATE TABLE FACT

	--RE-ADD FOREIGN KEY CONSTRAINT
	ALTER TABLE FACT
	ADD CONSTRAINT FACT_FK FOREIGN KEY (AC_ID) REFERENCES AIRCRAFTDIM (AC_ID),
			   FOREIGN KEY (PILOT_ID) REFERENCES PILOTDIM (PILOT_ID),
			   FOREIGN KEY (TIME_ID) REFERENCES TIMEDIM (TIME_ID)
	
	--POPULATE AIRCRAFTDIM
	INSERT INTO AIRCRAFTDIM 
	SELECT	MOD_CODE, MOD_NAME
	FROM	MODEL 
	--POPULATE PILOTDIM
	INSERT INTO PILOTDIM
	SELECT	P.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME
	FROM	PILOT P INNER JOIN EMPLOYEE E ON P.EMP_NUM = E.EMP_NUM
	--POPULATE TIMEDIM
	INSERT INTO TIMEDIM
	SELECT	CHAR_DATE, YEAR(CHAR_DATE), MONTH(CHAR_DATE), DAY(CHAR_DATE)
	FROM	CHARTER
	--POPULATE STAGING
	INSERT INTO STAGING (FUELUSED , DISTANCE ,REVENUE , MOD_CODE, MOD_NAME , EMP_NUM , EMP_LNAME , EMP_FNAME , CHAR_DATE , CHAR_YEAR , CHAR_MONTH , CHAR_DAY )
	SELECT CH.CHAR_FUEL_GALLONS, CH.CHAR_DISTANCE, CHAR_FUEL_GALLONS * MOD_CHG_MILE, M.MOD_CODE, M.MOD_NAME, P.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME, CH.CHAR_DATE, YEAR(CH.CHAR_DATE), MONTH(CH.CHAR_DATE), DAY(CH.CHAR_DATE)
	FROM MODEL M INNER JOIN AIRCRAFT A ON M.MOD_CODE = A.MOD_CODE
				 INNER JOIN CHARTER CH ON A.AC_NUMBER = CH.AC_NUMBER
				 INNER JOIN CREW C ON CH.CHAR_TRIP = C.CHAR_TRIP
				 INNER JOIN EMPLOYEE E ON C.EMP_NUM = E.EMP_NUM
				 INNER JOIN PILOT P ON E.EMP_NUM = P.EMP_NUM

	--UPDATING THE STAGING TABLE TO INCLUDE DWKEYS SO FACT TABLE CAN BE POPULATED
	UPDATE	STAGING
	SET		PILOT_ID = P.PILOT_ID
	FROM	STAGING S INNER JOIN PILOTDIM P ON S.EMP_NUM = P.EMP_NUM

	UPDATE	STAGING
	SET		AC_ID = A.AC_ID
	FROM	STAGING S INNER JOIN AIRCRAFTDIM A ON S.MOD_CODE = A.MOD_CODE

	UPDATE	STAGING
	SET		TIME_ID = T.TIME_ID
	FROM	STAGING S INNER JOIN TIMEDIM T ON S.CHAR_DATE = T.CHAR_DATE

	--POPULATING THE FACT TABLE FROM STAGING
	INSERT INTO FACT 
	SELECT AC_ID, PILOT_ID, TIME_ID, FUELUSED, DISTANCE, REVENUE
	FROM	STAGING

END

--DROP PROCEDURE A10SP