
SELECT	P.EMP_FNAME
FROM	FACT F INNER JOIN PILOTDIM P ON F.PILOT_ID = P.PILOT_ID
WHERE	DISTANCE = (SELECT TOP 1 DISTANCE
						 FROM	FACT
						 ORDER BY DISTANCE DESC
						 )

SELECT	REVENUE
FROM	FACT F INNER JOIN AIRCRAFTDIM A ON F.AC_ID = A.AC_ID
		INNER JOIN TIMEDIM T ON T.TIME_ID = F.TIME_ID
ORDER BY MOD_NAME ASC,
		 MONTH(CHAR_DATE) ASC